.TH all-backup.sh 8 "2009-02-01" Pfn\ Backup
.SH NAME 
all-backup.sh \(em Perform a complete backup (incremental)
.SH SYNOPSIS 
.B all-backup.sh

.SH DESCRIPTION 
.B all-backup.sh
Performs a backup for each user and section defined in the backup configuration
file (see. pfn_backup-all.cfg(5) )

.SH EXAMPLE
  # all-backup.sh
  
  This will start the backup.
  
.SH NOTE
If the backup index contains a line like "Need full postgress backup", among its
last 3 lines, then 
.B all-backup.sh
will also perform a full, warm, backup of postgresql server, using the PITR method.

.SH SEE ALSO 
pfn_backup-all.cfg(5), pfn_backup-options(5), user-backup.sh(1)

.SH AUTHOR 

This manual page was written by Panos Christeas <xrg@hellug.gr>
Permission is granted to copy, distribute and/or modify this document under 
the terms of the GNU General Public License, Version 2 any  
later version published by the Free Software Foundation. 
