.TH multistage-backup.sh 8 "2009-02-01" Pfn\ Backup
.SH NAME 
multistage-backup.sh \(em Perform all stages of backup
.SH SYNOPSIS 
.B multistage-backup.sh

.SH DESCRIPTION 
.B multistage-backup.sh
Performs a backup and all subsequent stages (encryption, transfers).
see. pfn_backup-all.cfg(5)

multistage-backup.sh is suitable for a cronjob (see cron(8)), since
it performs all jobs needed for a daily backup.


.SH EXAMPLE
  # multistage-backup.sh
  
  This will start the backup.
  
.SH SEE ALSO 
pfn_backup-all.cfg(5), pfn_backup-options(5), user-backup.sh(1)

.SH AUTHOR 

This manual page was written by Panos Christeas <p_christ@hol.gr>
Permission is granted to copy, distribute and/or modify this document under 
the terms of the GNU General Public License, Version 2 any  
later version published by the Free Software Foundation. 
